name: Build and push to GitHub OCI registry

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.key"

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # ratchet:docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # ratchet:docker/setup-buildx-action@v2
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "img_tag=ttl.sh/${{ github.repository }}:2h" >> ${GITHUB_OUTPUT}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # ratchet:docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: false
          tags: ${{ steps.dockertag.outputs.img_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
